<a href="https://colab.research.google.com/github/Saaraansh10/Breast-Cancer-Data-Classification/blob/main/DataMiningReport.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary libraries and performing ***Classification*** on the same dataset using ***Weak Learner*** and ***Strong Learner***.




Weak Learner used:- ***Logistic Regression***





Strong Learner used:- ***XGBoost***

In [2]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


Weak Learner Usage :- Logistic Regression

Converting our data file saved in the folders from .data to .csv

In [37]:
#converting .Data file to .csv
original_file = "breastcancer.data"

csv_file = "breastcancer.csv"

delimiter = ','

column_names = ["Sample code number","Clump thickness","Uniformity of cell size","Uniformity of cell shape","Marginaln adhesion","Single epithelial cell size","Bare nuclei","Bland chromatin","Normal nucleoli","Mitoses","Class"]
df = pd.read_csv(original_file,delimiter = delimiter,header =None,names = column_names)

df.to_csv(csv_file,index = False)

Getting the dataset in .csv format as input

In [38]:
#getting the dataset

dataset = pd.read_csv("breastcancer.csv", na_values='?')

X = dataset.iloc[:,1:-1].values
Y = dataset.iloc[:,-1].values


Imputing the missing values

In [39]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X)
X = imputer.transform(X)

Applying the training and testing split

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.35, random_state = 0)

Finally applying the weak Learner

In [41]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

Predicting the Results

In [42]:
Y_prediction = classifier.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, Y_prediction)

print(cm)
accuracy_score(Y_test, Y_prediction)

[[149   7]
 [  5  84]]


0.9510204081632653

Calculating the Accuracy and Standard Deviation using k_fold cross-variation

In [44]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier,X= X_train,y= Y_train,cv =10)
print("Accuracy : {:.2f} %".format(accuracies.mean()*100))

print("Standard Deviation : {:.2f}%".format(accuracies.std()*100))

Accuracy : 97.14 %
Standard Deviation : 1.97%


Stronger Learner Usage :- XGBoost

We are going to use same data set and preprocessing is already done above

Using Label Encoder on Y

In [46]:
from sklearn.preprocessing import LabelEncoder
df = LabelEncoder()
Y_train = df.fit_transform(Y_train)

Training the Dataset

In [47]:
from xgboost import XGBClassifier

xgb = XGBClassifier()
xgb.fit(X_train,Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

Predicting and Inversing the dataset

In [49]:
y_pred = xgb.predict(X_test)
y_pred = df.inverse_transform(y_pred)

Calculating the confusion matrix

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score
cmtrx = confusion_matrix(Y_test,y_pred)


print(cmtrx)
accuracy_score(Y_test,y_pred)

[[  0   0   0   0]
 [  0   0   0   0]
 [149   7   0   0]
 [  4  85   0   0]]


0.0

Finally finding out the accuracy and standard deviation using k_fold cross-variation

In [51]:
from sklearn.model_selection import cross_val_score
accuracie = cross_val_score(estimator=xgb,X= X_train,y= Y_train,cv =10)
print("Accuracy : {:.2f} %".format(accuracies.mean()*100))

print("Standard Deviation : {:.2f}%".format(accuracies.std()*100))

Accuracy : 97.14 %
Standard Deviation : 1.97%
